### ISSUE TITLE
blockspring push changes newlines of block.py on windows platform

### ISSUE THREAD

**Issue by dreftymac** [blockspring/blockspring.rb#2]
Problem: 

Running blockspring push on a windows machine causes the newlines in block.py to be replaced with Windows newlines instead of Linux style.

Question: 

Is there a patch for blockspring.rb that will respect the currently-set newlines in the file and not modify them?

**Comment by pkpp1233** [comment]
@jason - is this happening in here https://github.com/blockspring/blockspring-cli/blob/master/lib/blockspring/cli/command/block.rb#L95?

Git runs into the same problem: https://help.github.com/articles/dealing-with-line-endings/.

PS - Sorry for the confusion, @dreftymac. We haven't open-sourced the CLI tool, but need to asap.

**Comment by dreftymac** [comment]
No problem Paul. I can write a post-processor that changes them back independently, or just use a gitconfig file. Not a problem at all, thanks for the info.

**Comment by pkpp1233** [comment]
Oh no worries @dreftymac! Thanks for opening the issue. Working on fix now. Will let you know when ready. You shouldn't have to do any post-processing!
